name: DVC Pipeline
on:
  push:
    branches:
      - master

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # first setting up uv
      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.5.26'
          enable-cache: true
          
      # setting up python using uv
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      # installing dependencies
      - name: Install dependencies
        run: |
          uv sync

      # run dvc pipeline
      - name: Run DVC pipeline
        run: |
          dvc repro